### PR TITLE
[WIP]confirm .go coding style with github action

### PR DESCRIPTION
**Pull request by jjmengze**
# Description

/kind feature
It will setup a pipeline to check .Go format for each pr with github action.

## Issues to fix

Please link issues this PR will fix: \
#58 

## Does this PR introduce a user-facing change?:
```
none
```

## Reminding
Something you can do before PR to reduce time to merge

* run "make build" to build the code
* run "make format" to reformat the code
* run "make lint" if you are using unix system
* run "make test-integration" to pass all tests

### CODE REVIEW

**Comment by jjmengze** [comment]
This ci pipeline will only be triggered when there is a change in .go and gomodule

**Comment by jjmengze** [comment]
let's modify some .go coding style to check the pipeline result.
change the data.go format
```go

package youtube

type PlayerResponseData struct {
           	PlayabilityStatus struct {
		Status          string `json:"status"`
		Reason          string `json:"reason"`
		PlayableInEmbed bool   `json:"playableInEmbed"`
		ContextParams   string `json:"contextParams"`
	} `json:"playabilityStatus"`
...
```

This change will trigger ci pipeline who will tell us where the format is wrong.
The result following as below.
image

**Comment by jjmengze** [comment]
/cc @kkc @kkc 
If you don’t mind, could you please review this pr and give me some suggestion?

**Comment by kkc** [comment]
I am thinking should we use our Makefile with Github action. That could be easier to test each step locally. What do you think?

**Comment by Julian-Chu** [comment]
hi @jjmengze ,   thank for the PR.
just remind something you and @kkc  may be missing.

We prefer  golangci-lint to handle all checkers, it's easy to use and  more powerful than gofmt, please find the following link for reference:
https://golangci-lint.run/usage/linters/

so based on  golangci-lint, I have 2 ways in my mind:
-  use Makefile which kkc alreadys setup golangci-lint , it's simple either local or github action.
or 
- use golangci-lint github action , it might be better to integrate with Github

ps: it is still open for discussion

**Comment by jjmengze** [comment]
Sorry for the late reply @kkc @Julian-Chu 

Thank you for your suggestions. After careful consideration, using lint provided by the makefile will be a better way.
BTW,the visual results of the originally proposed method may be easier to read.  😆  😆

**Comment by kkc** [comment]
looking forward to seeing this GitHub action integration.  :smirk:
I think we can take a look at this CNCF project `Thanos` which also adapts GitHub action to perform lintify. https://github.com/thanos-io/thanos/blob/master/.github/workflows/go.yaml

**Comment by jjmengze** [comment]
@kkc 
Sorry for replying to this message so late. I have found a lot of various methods about go Github action these days.
As far as the current youtube project is concerned, it may be a good practice to use a ready-made makefile and golangci-lint.
If you don’t mind, you can refer to the current Commit

**Comment by kkc** [comment]
@jinweijie hi, it takes me for a while to think how to integrate this with Github actions. I will start implementing it. I hope you can still give us some suggestions:)

**Comment by Julian-Chu** [comment]
closed by #76

**Pull request closed without merging**
