### PR TITLE
Playlists revived

### PR DESCRIPTION
**Pull request by elProxy**
# Description

Picked up and reworked the PR #105 from @clr1107.

## Issues to fix

Please link issues this PR will fix: \
\#102

if no relevant issue, but this will fix something important for reference
, please free to open an issue.

## Reminding
Something you can do before PR to reduce time to merge

* run "make build" to build the code
* run "make format" to reformat the code
* run "make lint" if you are using unix system
* run "make test-integration" to pass all tests

### CODE REVIEW

**Review by corny — APPROVED** [review]
Looks good to me. I did a little bit of refactoring.

**Comment by itscaro** [comment]
@elProxy 

I ran into 404 with the YT ajax endpoint

For the test playlist: https://www.youtube.com/playlist?list=PLQZgI7en5XEgM0L1_ZcKmEzxW1sCOVZwP

https://youtube.com/list_ajax?style=json&action_get_list=1&list=PLQZgI7en5XEgM0L1_ZcKmEzxW1sCOVZwP&hl=en

image

**Comment by elProxy** [comment]
> @elProxy
> 
> I ran into 404 with the YT ajax endpoint
> 
> For the test playlist: https://www.youtube.com/playlist?list=PLQZgI7en5XEgM0L1_ZcKmEzxW1sCOVZwP
> 
> https://youtube.com/list_ajax?style=json&action_get_list=1&list=PLQZgI7en5XEgM0L1_ZcKmEzxW1sCOVZwP&hl=en
> 
> image

@itscaro thanks for the heads up...
Good point, this is kind of embarrassing: I didn't bother to play with this again, it appears it broke in February (I last used it around the christmas holidays, and was going to need this for another project).
Seems like the new approach will mean fetching that data from inline JS in the html document. I'll see if I can come up with a fix in the next few days. 
I also wanted to add support to the `youtubedr` command, should have done that first, would have made it trivial to detect the issue.

**Comment by itscaro** [comment]
@elProxy I was trying to do parsing a few months early. I found some of my work and put here #161

**Comment by elProxy** [comment]
> @elProxy I was trying to do parsing a few months early. I found some of my works and put them here #161

@itscaro Try this ;)
https://github.com/kkdai/youtube/pull/163

**Comment by clr1107** [comment]
Lovely to see this addition rescued from my lack of time haha. Might end up using the library again soon so this is welcomed.

**Comment by elProxy** [comment]
> Lovely to see this addition rescued from my lack of time haha. Might end up using the library again soon so this is welcomed.

Based on the conversation above, I’m sure more contributors to maintain it will also not be a luxury.

**Comment by itscaro** [comment]
> > @elProxy I was trying to do parsing a few months early. I found some of my works and put them here #161
> 
> @itscaro Try this ;)
> https://github.com/kkdai/youtube/pull/163

Thank you :)
I will try to do something like that for channel page, so far I use regex to parse. I'm doing a daemon to download new videos from channel page.

**Pull request merged**
