### PR TITLE
Playlists

### PR DESCRIPTION
**Pull request by clr1107**
# Description
Added the ability to use YouTube playlists, as closely as possible mirroring the `Video` api, and making minimal changes to the pre-existing `Video` infrastructure.

## Issues to fix
Playlists, #102 
No commands are added at this stage, I can do that too, if you'd like. But internally, it (should) all be finished.

## Testing
The tests (some) failed, I suspect this is due to issue #104

### CODE REVIEW

**Comment by corny** [comment]
I think we should not use the `Video` struct for playlist entries. This would allow to pass incomplete videos zu the Client. Why not creating a `PlaylistEntry` struct?

**Comment by clr1107** [comment]
> I think we should not use the `Video` struct for playlist entries. This would allow to pass incomplete videos zu the Client. Why not creating a `PlaylistEntry` struct?

I was going to, but decided against it, as it'd be a needless abstraction. Instead I included the `Loaded` field, as shown. Its use is also shown in the example I added in `example_test.go`. 

There are three states: `NotLoaded`, `WeaklyLoaded`, and `FullyLoaded`. `WeaklyLoaded` indicates it was loaded from a playlist (or by some other method in the future) and that not all the information is there, in this case we know that the metadata required to download is not there. So one must fully load it, which is now possible by a function I created and exposed.

**Review by corny — CHANGES_REQUESTED** [review]
Please:
- Use camelCase and not under_score
- Rebase on top of the current master
- Use httpGetBodyBytes where possible
- Don't do string interpolation with `strings.Replace`. Use `fmt.Sprintf()` and only do it once.

I'm not convinced yet that we should pass a `Client` to a method of `Video`. I'll think about other ways.

**Comment by clr1107** [comment]
Note: to my knowledge I had removed all underscored variables in one of the commits previously, I can't find any now. If I somehow missed one please direct me to it :) I'm not sure why I even did that, god knows what language I was using in the past few days...

**Comment by weeee9** [comment]
@clr1107 
>Note: to my knowledge I had removed all underscored variables in one of the commits previously, I can't find any now. If I somehow missed one please direct me to it :) I'm not sure why I even did that, god knows what language I was using in the past few days...

like `TestYoutube_extractPlaylistID` in `playlist_test.go` ?

**Comment by clr1107** [comment]
> @clr1107
> 
> > Note: to my knowledge I had removed all underscored variables in one of the commits previously, I can't find any now. If I somehow missed one please direct me to it :) I'm not sure why I even did that, god knows what language I was using in the past few days...
> 
> like `TestYoutube_extractPlaylistID` in `playlist_test.go` ?

@weeee9  There's also `response_data.go` and `itag_test.go`. File names are fine iirc, especially for testing the convention is that it's `package_test.go` or smth. As for the method names in tests those are auto-generated by gotests; IntelliJ does it as does VS Code :)

**Comment by clr1107** [comment]
Sorry, is this getting merged?

**Comment by Julian-Chu** [comment]
> Sorry, is this getting merged?

hi @clr1107  , thank for PR.
There's still conflict, could you solve it first?  We will review new changes soon.

**Comment by Julian-Chu** [comment]
some tests are failed because now youtube has both single and double quote for embedded body in different videos.
I will fix the test by new PR. Please ignore the failed tests in this PR.

@corny  , I see @clr1107  have already done  some requested changes, still some changes to finish?

**Comment by LordRusk** [comment]
This would be awesome, im not sure what still has to be done for it to be merged, but this would make this api 10/10

**Comment by Julian-Chu** [comment]
any update here?   the PR  has been opened for a long time and codebase has a lot of change. If no update here,  I suggest to close this PR and open new one instead of working on this one.

**Comment by clr1107** [comment]
> any update here?   the PR  has been opened for a long time and codebase has a lot of change. If no update here,  I suggest to close this PR and open new one instead of working on this one.

No updates, I've had no time sorry. It was ready to merge a long time ago but I suppose it just never was. I no longer have time to recreate it, so I can't redo it.

Thanks.

**Pull request closed without merging**
