### PR TITLE
Completely new cache

### PR DESCRIPTION
**Pull request by Camelva**
# Description
**IMO this is more like a draft, and any discussion is welcomed**

Completely new cache instead of old `DecipherOperationsCache`. Now it stores version of current youtube player, signatureTimestamp and deciphering operations.

Some key points:

- as i found, player version is "global", so every video should use same version
- i tried to make some benchmarks. and it seems like fetching embed page (without videoId) is the most efficient way (video embed page is second next), But i still would be glad to find some another way to fetch current player's version without parsing html :sigh:.

Also i plan to add some mechanism to save backup of this cache locally and somehow import it on start.

Another thing i'm thinking about - maybe store player version temporarily with relatively short expiration time (few minutes, maybe hour?) instead of fetching it for each song, Though fetching only player's version instead of whole player, sts and decipherOps is already win, but still can be better.

## Issues to fix

Please link issues this PR will fix: \
\#200

if no relevant issue, but this will fix something important for reference
, please free to open an issue.

## Reminding
Something you can do before PR to reduce time to merge

* run "make build" to build the code
* run "make format" to reformat the code
* run "make lint" if you are using unix system
* run "make test-integration" to pass all tests

### CODE REVIEW

**Comment by Camelva** [comment]
Alright, now it can store cache locally at file from `CacheStorage` variable. This variable is exported so user can easily change location or even disable local cache by passing empty string. Still unsure about caching player version. Maybe will add in future..

**Comment by Camelva** [comment]
Interesting how i run tests again and again locally and they pass, but here i got error. I suppose there is some element of randomness..
Can i somehow run tests here again without additional commit? 

_Also i see how this pr was mentioned, but can't find actual mention. Huh_

**Comment by Camelva** [comment]
Alright, reverted commit with additional test since it's weird

**Comment by Julian-Chu** [comment]
hi @Camelva , thanks for PR, sorry too busy . if other maintainers are busy as well.
I will review this PR in two weeks.  Have a nice day!

**Comment by Julian-Chu** [comment]
a small question,  is it possible to have same version but with different decipher operations?

cache is difficult,  still no clear idea for this pr. :exploding_head:

**Pull request closed without merging**
